# -*- coding: utf-8 -*-
"""Final_Project_Skyrec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m8nPFs6xZU1hOTl3CYBluYl5clgJDmZA
"""

# Cell 1: Import necessary libraries for the ML Pipeline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Sklearn modules for preprocessing and splitting
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Sklearn models
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

# Sklearn metrics for evaluation
from sklearn.metrics import accuracy_score, precision_score, f1_score, classification_report, confusion_matrix

# Joblib for model saving (Deployment)
import joblib

# Cell 2: File Upload
from google.colab import files

print("Please upload your CSV file...")
uploaded = files.upload()

# Cell 3: Load the uploaded dataset into a DataFrame
import pandas as pd
import io

file_name = list(uploaded.keys())[0]
df = pd.read_excel(io.BytesIO(uploaded[file_name]))

print(f"\n✅ '{file_name}' successfully loaded into DataFrame!")

df.head()

df.info()

# Cell 4: Data Pre-processing
print("Starting Data Cleaning...")

# 1. Drop useless columns (wadak nathi columns ain kirima)
columns_to_drop = ['CustomerID', 'Count', 'Lat Long', 'Country', 'State', 'City', 'Zip Code']
df = df.drop(columns=[col for col in columns_to_drop if col in df.columns], errors='ignore')

# 2. Fix 'Total Charges' column (Numbers walata harawamu, his than NaN wenawa)
df['Total Charges'] = pd.to_numeric(df['Total Charges'], errors='coerce')

# 3. Fill missing values in 'Total Charges' with the median value (his than median eken fill karamu)
df['Total Charges'] = df['Total Charges'].fillna(df['Total Charges'].median())

# 4. Drop any duplicate rows (samana rows ain karamu)
df = df.drop_duplicates()

print("✅ Data Cleaning Complete!")
print(f"Dataset shape after cleaning: {df.shape}")

# Check if there are any missing values left
missing_values = df.isnull().sum().sum()
print(f"Total missing values remaining: {missing_values}")

# Cell 5: Feature Engineering & Data Splitting
print("Starting Feature Engineering...")

# 1. Encode Target Variable (Churn Label: Yes->1, No->0)
df['Churn Label'] = df['Churn Label'].map({'Yes': 1, 'No': 0})

# 2. Encode other categorical features using One-Hot Encoding
df_encoded = pd.get_dummies(df, drop_first=True)

# 3. Define Features (X) and Target (y)
X = df_encoded.drop('Churn Label', axis=1)
y = df_encoded['Churn Label']

# 4. Split the data (80% for training, 20% for testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 5. Scale the features (Normalize data)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("✅ Feature Engineering & Splitting Complete!")
print(f"Training data shape (Rows, Columns): {X_train_scaled.shape}")
print(f"Testing data shape (Rows, Columns): {X_test_scaled.shape}")

# Cell 6: Model Training & Selection
print("Starting Model Training...\n")

# Define the models based on the proposal
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42)
}

best_model = None
best_accuracy = 0
best_model_name = ""

# Train and evaluate each model
for name, model in models.items():
    # Train the model
    model.fit(X_train_scaled, y_train)

    # Make predictions on the test set
    y_pred = model.predict(X_test_scaled)

    # Calculate accuracy
    acc = accuracy_score(y_test, y_pred)
    print(f"{name} Accuracy: {acc:.4f}")

    # Check if this model is the best one so far
    if acc > best_accuracy:
        best_accuracy = acc
        best_model = model
        best_model_name = name

print(f"\n🏆 Best Model Selected: {best_model_name} with an Accuracy of {best_accuracy:.4f}")

# Cell 7: Model Evaluation
print(f"--- Evaluating {best_model_name} ---")

# Best model eken test data walata predictions ganna
y_pred_best = best_model.predict(X_test_scaled)

print("\nClassification Report:")
print(classification_report(y_test, y_pred_best))

# Precision saha F1-Score eka wena wenama ganna
precision = precision_score(y_test, y_pred_best)
f1 = f1_score(y_test, y_pred_best)
print(f"Precision: {precision:.4f}")
print(f"F1-Score: {f1:.4f}")

# Confusion Matrix eka lassanata plot karanna
print("\nConfusion Matrix Plot:")
cm = confusion_matrix(y_test, y_pred_best)
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title(f'Confusion Matrix - {best_model_name}')
plt.show()

# Cell 8: Save Model and Preprocessing Objects
import joblib

print("Saving models for deployment...")

# 1. Save the trained best model (Logistic Regression)
joblib.dump(best_model, 'churn_prediction_model.pkl')

# 2. Save the scaler (Backend eken ena aluth data scale karanna meka oni wenawa)
joblib.dump(scaler, 'scaler.pkl')

# 3. Save the feature columns (Backend eke data columns wala piliwela hariyata thiyaganna meka oni)
joblib.dump(X.columns.tolist(), 'model_columns.pkl')

print("✅ Model, Scaler, and Columns saved successfully!")
print("Files created: churn_prediction_model.pkl, scaler.pkl, model_columns.pkl")